### ISSUE TITLE
Allow users to specify remote name

### ISSUE THREAD

**Issue by jbrauer** [douggreen/drupal-composer-installer#4]
It would be very handy to be able to specify the remote name instead of requiring that it be 'origin'. For any number of reasons it may be preferable to make the branches on a remote with a different name. Perhaps in https://github.com/douggreen/drupal-composer-installer/blob/master/src/Drupal/Composer/DrupalInstallerPlugin.php#L95 it could use an environment variable if set to determine the remote name.

**Comment by douggreen** [comment]
Add in https://github.com/douggreen/drupal-composer-installer/commit/05c2eb7c669921d90a2b60e78aa5032bababebdc
